/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'ink-black': '#0a0a0a',
        'mystic-azure': '#1a1a2e',
        'deep-ink': '#0f0f1a',
        'dark-jade': '#0d1f12',
        'scroll-parchment': '#1a1a1a',
        'faded-gold': '#2a2418',
        'spirit-silk': '#1e1e2e',
        'celestial-gold': '#d4a843',
        'spirit-cyan': '#22d3ee',
        'mystic-purple': '#7c3aed',
        'jade-green': '#10b981',
        'vermil-red': '#dc2626',
        'fire-vein': '#ea580c',
        'scroll-white': '#e2e8f0',
        'mist-gray': '#94a3b8',
        'faded-ink': '#6b7280',
        'vitality-red': '#991b1b',
        'spirit-blue': '#1e3a5f',
        'cultivation-gold': '#92400e',
      },
      fontFamily: {
        title: ['"ZCOOL XiaoWei"', '"Ma Shan Zheng"', 'serif'],
        body: ['"Noto Serif SC"', 'serif'],
        ui: ['Inter', 'sans-serif'],
      },
      boxShadow: {
        'celestial-glow': '0 0 15px rgba(212, 168, 67, 0.4)',
        'spirit-glow': '0 0 15px rgba(34, 211, 238, 0.3)',
        'purple-mist': '0 0 15px rgba(124, 58, 237, 0.3)',
        'inner-light': 'inset 0 0 30px rgba(212, 168, 67, 0.05)',
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-out',
        'slide-up': 'slideUp 0.4s ease-out',
        'pulse-glow': 'pulseGlow 3s infinite',
        'float': 'float 6s ease-in-out infinite',
        'spirit-drift': 'spiritDrift 20s ease-in-out infinite',
      },
      keyframes: {
        fadeIn: { '0%': { opacity: '0' }, '100%': { opacity: '1' } },
        slideUp: { '0%': { opacity: '0', transform: 'translateY(10px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        pulseGlow: { '0%, 100%': { boxShadow: '0 0 8px rgba(212, 168, 67, 0.2)' }, '50%': { boxShadow: '0 0 20px rgba(212, 168, 67, 0.5)' } },
        float: { '0%, 100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-5px)' } },
        spiritDrift: { '0%, 100%': { transform: 'translateY(0) scale(1)', opacity: '0.3' }, '50%': { transform: 'translateY(-15px) scale(1.05)', opacity: '0.6' } },
      },
    },
  },
  plugins: [],
};
